#version: '3.8'
#
#services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: lotto-rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: lotto-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1618
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lotto-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1618

  draw-service:
    build: ./draw-service
    container_name: draw-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/drawdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1618
      SPRING_RABBITMQ_HOST: rabbitmq

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - rabbitmq
      - draw-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1618
      SPRING_RABBITMQ_HOST: rabbitmq
      DRAW_SERVICE_URL: http://draw-service:8081

volumes:
  postgres-data:
